### ISSUE TITLE
How to close with out-side menu clicking?

### ISSUE THREAD

**Issue by iagokrt** [Codebrahma/react-flexible-sliding-menu#2]
I really really really enjoyed how easy you made my life.
The docs is awesome. The project is the best i found of easy implement slide menu solution. I can add another exemple of how i implemented. making it yet easier.
Anyway. I wanna know there is a way of closing the menu by click outside it?

**Comment by DivyanshBatham** [comment]
@iagokrt Yes you can make the menu close when clicking outside, all you need to do is in `<YourMenuComponent>` create a clickable overlay and add `onClick={closeMenu}` to that.

**Comment by Kameshwaran** [comment]
you may add a click listener on document. Inside the listener if the clicked target is not the menu, you can close the menu.

**Comment by MustaphaMiah** [comment]
is there a way of making the menu slide from right to left?

**Comment by DivyanshBatham** [comment]
@MustaphaMiah You can pass `direction="right"` to `<MenuProvider>`. It will look like this:

```
<MenuProvider direction="right">
  <App />
</MenuProvider>
```

**Comment by DivyanshBatham** [comment]
@MustaphaMiah For more props look at the MenuProvider [Props](https://react-flexible-sliding-menu.netlify.app/API/MenuProvider#props)
